### ISSUE TITLE
A detail while printing PgNode_s

### ISSUE THREAD

**Issue by jganzabal** [udacity/AIND-Planning#3]
https://github.com/udacity/AIND-Planning/blob/master/my_planning_graph.py#L87
I think there is a minor bug while showing the PgNode_s at line 87 of my_planning_graph.py, the ~ shouldnt be there for the positive case

print("\n*** ~{}".format(self.symbol))

**Comment by cgearhart** [comment]
Good catch. Should be fixed now. Thanks!
